packages:
  - "apps/*"
allowBuilds:
  "@swc/core": true
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@strapi/admin@5.50.2"
  - "@strapi/cloud-cli@5.50.2"
  - "@strapi/content-manager@5.50.2"
  - "@strapi/content-releases@5.50.2"
  - "@strapi/content-type-builder@5.50.2"
  - "@strapi/core@5.50.2"
  - "@strapi/data-transfer@5.50.2"
  - "@strapi/database@5.50.2"
  - "@strapi/email@5.50.2"
  - "@strapi/generators@5.50.2"
  - "@strapi/i18n@5.50.2"
  - "@strapi/logger@5.50.2"
  - "@strapi/openapi@5.50.2"
  - "@strapi/permissions@5.50.2"
  - "@strapi/plugin-cloud@5.50.2"
  - "@strapi/plugin-users-permissions@5.50.2"
  - "@strapi/provider-email-sendmail@5.50.2"
  - "@strapi/provider-upload-local@5.50.2"
  - "@strapi/review-workflows@5.50.2"
  - "@strapi/strapi@5.50.2"
  - "@strapi/types@5.50.2"
  - "@strapi/typescript-utils@5.50.2"
  - "@strapi/upload@5.50.2"
  - "@strapi/utils@5.50.2"
