{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "home-showcase.fullname" . }}
  labels:
    {{- include "home-showcase.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: {{ include "home-showcase.fullname" . }}-cms
                port:
                  number: {{ .Values.cms.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "home-showcase.fullname" . }}-cms
                port:
                  number: {{ .Values.cms.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "home-showcase.fullname" . }}-web
                port:
                  number: {{ .Values.web.port }}
{{- end }}
