apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-showcase.fullname" . }}-postgres
  labels:
    {{- include "home-showcase.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
