apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-showcase.fullname" . }}-web
  labels:
    {{- include "home-showcase.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      name: http
