import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "build/**",
      ".strapi/**",
      ".cache/**",
      "node_modules/**",
      // Auto-regenerated by Strapi on every `develop`/`build`, not hand-authored.
      "types/generated/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    // Strapi's generated config files use a `({ env }) => ({...})` signature
    // for every config module even when `env` isn't needed by that module.
    // Scoped to config/ only so a real unused-argument bug in src/ (e.g. an
    // unused ctx/event in a controller or lifecycle hook) still gets caught.
    files: ["config/**/*.ts"],
    rules: {
      "@typescript-eslint/no-unused-vars": ["error", { args: "none" }],
    },
  },
);
